name: bombsquad
base: core20
version: '1.7.28'
summary: Bomb Squad
description: |
  8 Player Party Game Madness!
  Blow up your friends in mini-games ranging from capture-the-flag to hockey.
  Featuring gratuitous explosions, advanced ragdoll face-plant physics,
  pirates, ninjas, barbarians, insane chefs, and more. Supports PS3 controllers,
  XBox 360 controllers, most USB/Bluetooth gamepads, and even iOS and Android
  devices as controllers via the free 'BombSquad Remote' app. Bombs Away!
grade: stable
confinement: strict
architectures:
  - build-on: amd64
apps:
  bombsquad:
    extensions: [ gnome-3-38 ]
    environment:
      ALSA_CONFIG_PATH: "$SNAP/etc/asound.conf"
      PYTHONHOME: "$SNAP/usr"
      LIBGL_DRIVERS_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri"
      LD_LIBRARY_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/mesa:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/mesa-egl:/var/lib/snapd/lib/gl"
      __EGL_VENDOR_LIBRARY_DIRS: "/var/lib/snapd/lib/glvnd/egl_vendor.d:$__EGL_VENDOR_LIBRARY_DIRS"
    command: bin/launcher
    plugs:
      - alsa
      - x11
      - opengl
      - desktop
      - network
      - network-bind
      - audio-playback
      - joystick
      - screen-inhibit-control


layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib

package-repositories:
 - type: apt
   ppa: deadsnakes/ppa

parts:
  launcher:
    plugin: dump
    source: snap/local
  bombsquad:
    after: [alsa-pulseaudio]
    plugin: dump
    source: https://files.ballistica.net/bombsquad/builds/BombSquad_Linux_x86_64_$SNAPCRAFT_PROJECT_VERSION.tar.gz
    stage-packages:
      - libopenal1
      - libbsd0
      - libffi7
      - libflac8
      - libgl1-mesa-dri
      - libgl1-mesa-glx
      - libglu1-mesa
      - liblz4-1
      - liblzma5
      - libogg0
      - libpython3.9
      - libsdl2-2.0-0
      - libsndio7.0
      - libvorbis0a
      - libvorbisfile3
      - libx11-6
      - libxau6
      - libxcb1
      - libxdmcp6
      - libopengl0
      - python3.11
      - libpython3.11
  alsa-pulseaudio:
    plugin: dump
    source: .
    override-pull: |
      mkdir etc -p
      cat > etc/asound.conf <<EOF
      pcm.!default {
          type pulse
          fallback "sysdefault"
          hint {
              show on
              description "Default ALSA Output (currently PulseAudio Sound Server)"
          }
      }
      ctl.!default {
          type pulse
          fallback "sysdefault"
      }
      EOF